# Generated by Django 5.0.7 on 2024-07-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0034_freeslot_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeslot',
            name='charges',
        ),
    ]
